### ISSUE TITLE
Blank webpage after UI install

### ISSUE THREAD

**Issue by steviecoaster** [armadito/armadito-web-ui#45]
I'm trying to get this up and running as a POC. 

I've installed the software on the latest version of Ubuntu following the Compile on linux docs. 

I'm getting the httpd daemon started, and when I got to localhost:8888/app/index.html, I see all the GET requests in the debug console window, but when it is done loading, all I get is a white page. No content whatsoever. 

I've tried it in Firefox that ships with Ubuntu as well as Chrome 56 from .deb. Both yield the same results. I can see all the code in Developer Tools, and everything looks like I should be seeing stuff....but I just have a white screen. Have I missed something? Is something broken? 

I used git clone https://github.com/armadito/armadito-web-ui.git -b DEV as the branch to clone from, as per the docs.

**Comment by vhamon** [comment]
Hello ! It seems to be due to a recent angularJs version. angular-animate works with angular version 1.414 , not with >= 1.5.  What angular version did you install ? You can see it in bower_components/angular/bower.json

I just updated bower.json in order to set 1.414 version in "resolutions" for dependencies conflicts.
Pulling last commits and running "bower update" should be fine.
In the future, we might get rid of angular1 because it is dying.

By the way, we have created a support category in our new forum on https://forum.armadito.org/.
You can login with your github account and create new topics in that category.

**Comment by fdechelle** [comment]
Hello,
Thanks for your feedback!
Currently, the window is no longer blank, however there are still things broken in the code and the interface does not communicate with the antivirus daemon. We are fixing this.

**Comment by steviecoaster** [comment]
That would be the issue. I've installed 1.6.2. I'll pull the latest commits and fix my angular version. Thanks for the response!

**Comment by steviecoaster** [comment]
I've fixed my install. I've got a web interface now! But you are correct.  I'm seeing several request to API calls and then processing warnings in the debug console output. 

If I can post any data that may help you track down these issues, let me know. This is a really cool project, so I'd like to see it get some traction.

**Comment by vhamon** [comment]
Thanks a lot. On-demand scan is now working again, we've just pushed fixes. Also, armadito-core and armadito-web-ui need to be rebuilt. Restarting daemons (armadito-httpd and armadito-scand) is also needed. 

There is still issues with status tab. It will be fixed soon, because it is due to protocol changes in daemons. We only need to update json parsing in web-ui Js services.
